version: '3'
services:
  db:
    image: mysql:5.7
    volumes:
      - ./app/db/mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: root
    ports:
      - "3306:3306"

  app:
    build: .
    command:
      [ "bash", "-c", "rm -f tmp/pids/server.pid; rails server -b 0.0.0.0" ]
    volumes:
      - .:/sampleapp
    ports:
      - "3000:3000"
    links:
      - db